//
//  FixedArraySize+Generated.swift
//  NKit
//
//  Created by Mejdej on 14/08/2025.
//

extension FixedArray {
    fileprivate init(
        e elements: Element...
    ) {
        self.init(Array(elements))!
    }
}

///  Content below is autogenerated with `generate_fixed_arrays.sh <max count>`
///# DO NOT CHANGE!!

public enum FixedArraySize1:  FixedArraySize { public static var count: Int {  1 } }
public enum FixedArraySize2:  FixedArraySize { public static var count: Int {  2 } }
public enum FixedArraySize3:  FixedArraySize { public static var count: Int {  3 } }
public enum FixedArraySize4:  FixedArraySize { public static var count: Int {  4 } }
public enum FixedArraySize5:  FixedArraySize { public static var count: Int {  5 } }
public enum FixedArraySize6:  FixedArraySize { public static var count: Int {  6 } }
public enum FixedArraySize7:  FixedArraySize { public static var count: Int {  7 } }
public enum FixedArraySize8:  FixedArraySize { public static var count: Int {  8 } }
public enum FixedArraySize9:  FixedArraySize { public static var count: Int {  9 } }
public enum FixedArraySize10: FixedArraySize { public static var count: Int { 10 } }
public enum FixedArraySize11: FixedArraySize { public static var count: Int { 11 } }
public enum FixedArraySize12: FixedArraySize { public static var count: Int { 12 } }
public enum FixedArraySize13: FixedArraySize { public static var count: Int { 13 } }
public enum FixedArraySize14: FixedArraySize { public static var count: Int { 14 } }
public enum FixedArraySize15: FixedArraySize { public static var count: Int { 15 } }
public enum FixedArraySize16: FixedArraySize { public static var count: Int { 16 } }
public enum FixedArraySize17: FixedArraySize { public static var count: Int { 17 } }
public enum FixedArraySize18: FixedArraySize { public static var count: Int { 18 } }
public enum FixedArraySize19: FixedArraySize { public static var count: Int { 19 } }
public enum FixedArraySize20: FixedArraySize { public static var count: Int { 20 } }
public enum FixedArraySize21: FixedArraySize { public static var count: Int { 21 } }
public enum FixedArraySize22: FixedArraySize { public static var count: Int { 22 } }
public enum FixedArraySize23: FixedArraySize { public static var count: Int { 23 } }
public enum FixedArraySize24: FixedArraySize { public static var count: Int { 24 } }
public enum FixedArraySize25: FixedArraySize { public static var count: Int { 25 } }
public enum FixedArraySize26: FixedArraySize { public static var count: Int { 26 } }
public enum FixedArraySize27: FixedArraySize { public static var count: Int { 27 } }
public enum FixedArraySize28: FixedArraySize { public static var count: Int { 28 } }
public enum FixedArraySize29: FixedArraySize { public static var count: Int { 29 } }
public enum FixedArraySize30: FixedArraySize { public static var count: Int { 30 } }

public typealias FixedArray1 <Element> = FixedArray<FixedArraySize1,  Element>
public typealias FixedArray2 <Element> = FixedArray<FixedArraySize2,  Element>
public typealias FixedArray3 <Element> = FixedArray<FixedArraySize3,  Element>
public typealias FixedArray4 <Element> = FixedArray<FixedArraySize4,  Element>
public typealias FixedArray5 <Element> = FixedArray<FixedArraySize5,  Element>
public typealias FixedArray6 <Element> = FixedArray<FixedArraySize6,  Element>
public typealias FixedArray7 <Element> = FixedArray<FixedArraySize7,  Element>
public typealias FixedArray8 <Element> = FixedArray<FixedArraySize8,  Element>
public typealias FixedArray9 <Element> = FixedArray<FixedArraySize9,  Element>
public typealias FixedArray10<Element> = FixedArray<FixedArraySize10, Element>
public typealias FixedArray11<Element> = FixedArray<FixedArraySize11, Element>
public typealias FixedArray12<Element> = FixedArray<FixedArraySize12, Element>
public typealias FixedArray13<Element> = FixedArray<FixedArraySize13, Element>
public typealias FixedArray14<Element> = FixedArray<FixedArraySize14, Element>
public typealias FixedArray15<Element> = FixedArray<FixedArraySize15, Element>
public typealias FixedArray16<Element> = FixedArray<FixedArraySize16, Element>
public typealias FixedArray17<Element> = FixedArray<FixedArraySize17, Element>
public typealias FixedArray18<Element> = FixedArray<FixedArraySize18, Element>
public typealias FixedArray19<Element> = FixedArray<FixedArraySize19, Element>
public typealias FixedArray20<Element> = FixedArray<FixedArraySize20, Element>
public typealias FixedArray21<Element> = FixedArray<FixedArraySize21, Element>
public typealias FixedArray22<Element> = FixedArray<FixedArraySize22, Element>
public typealias FixedArray23<Element> = FixedArray<FixedArraySize23, Element>
public typealias FixedArray24<Element> = FixedArray<FixedArraySize24, Element>
public typealias FixedArray25<Element> = FixedArray<FixedArraySize25, Element>
public typealias FixedArray26<Element> = FixedArray<FixedArraySize26, Element>
public typealias FixedArray27<Element> = FixedArray<FixedArraySize27, Element>
public typealias FixedArray28<Element> = FixedArray<FixedArraySize28, Element>
public typealias FixedArray29<Element> = FixedArray<FixedArraySize29, Element>
public typealias FixedArray30<Element> = FixedArray<FixedArraySize30, Element>

extension FixedArray {
    public init(
        _ _1: Element
    ) where Size == FixedArraySize1 {
        self.init(e: _1)
    }
    
    public init(
        _ _1: Element, _ _2: Element
    ) where Size == FixedArraySize2 {
        self.init(e: _1, _2)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element
    ) where Size == FixedArraySize3 {
        self.init(e: _1, _2, _3)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element
    ) where Size == FixedArraySize4 {
        self.init(e: _1, _2, _3, _4)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element
    ) where Size == FixedArraySize5 {
        self.init(e: _1, _2, _3, _4, _5)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element
    ) where Size == FixedArraySize6 {
        self.init(e: _1, _2, _3, _4, _5, _6)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element
    ) where Size == FixedArraySize7 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element
    ) where Size == FixedArraySize8 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element
    ) where Size == FixedArraySize9 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element
    ) where Size == FixedArraySize10 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element
    ) where Size == FixedArraySize11 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element
    ) where Size == FixedArraySize12 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element
    ) where Size == FixedArraySize13 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element
    ) where Size == FixedArraySize14 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element
    ) where Size == FixedArraySize15 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element
    ) where Size == FixedArraySize16 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element
    ) where Size == FixedArraySize17 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element
    ) where Size == FixedArraySize18 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element
    ) where Size == FixedArraySize19 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element
    ) where Size == FixedArraySize20 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element
    ) where Size == FixedArraySize21 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element
    ) where Size == FixedArraySize22 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element
    ) where Size == FixedArraySize23 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element, _ _24: Element
    ) where Size == FixedArraySize24 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element, _ _24: Element, 
        _ _25: Element
    ) where Size == FixedArraySize25 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element, _ _24: Element, 
        _ _25: Element, _ _26: Element
    ) where Size == FixedArraySize26 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element, _ _24: Element, 
        _ _25: Element, _ _26: Element, _ _27: Element
    ) where Size == FixedArraySize27 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element, _ _24: Element, 
        _ _25: Element, _ _26: Element, _ _27: Element, _ _28: Element
    ) where Size == FixedArraySize28 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, 
                  _25, _26, _27, _28)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element, _ _24: Element, 
        _ _25: Element, _ _26: Element, _ _27: Element, _ _28: Element, 
        _ _29: Element
    ) where Size == FixedArraySize29 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, 
                  _25, _26, _27, _28, _29)
    }
    
    public init(
        _ _1: Element, _ _2: Element, _ _3: Element, _ _4: Element, 
        _ _5: Element, _ _6: Element, _ _7: Element, _ _8: Element, 
        _ _9: Element, _ _10: Element, _ _11: Element, _ _12: Element, 
        _ _13: Element, _ _14: Element, _ _15: Element, _ _16: Element, 
        _ _17: Element, _ _18: Element, _ _19: Element, _ _20: Element, 
        _ _21: Element, _ _22: Element, _ _23: Element, _ _24: Element, 
        _ _25: Element, _ _26: Element, _ _27: Element, _ _28: Element, 
        _ _29: Element, _ _30: Element
    ) where Size == FixedArraySize30 {
        self.init(e: _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, 
                  _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, 
                  _25, _26, _27, _28, _29, _30)
    }
}
